# Generated by Django 4.1.6 on 2023-02-13 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "name",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("sector", models.CharField(max_length=30)),
                ("website", models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "symbol",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("price", models.FloatField()),
                ("recommendation_key", models.CharField(max_length=30, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stock.company"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candle", models.JSONField()),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stock.stock"
                    ),
                ),
            ],
        ),
    ]
