# Generated by Django 4.1.6 on 2023-02-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PriceHistory",
        ),
    ]
