# Generated by Django 4.1.6 on 2023-02-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_alter_stock_name_alter_stock_sector"),
    ]

    operations = [
        migrations.AddField(
            model_name="candle",
            name="volume",
            field=models.FloatField(default=0.0),
        ),
    ]
